"""First database migration: User, TypingResult, Paragraph, Friendship table

Revision ID: 871694d13302
Revises: 
Create Date: 2025-05-02 00:33:55.731448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871694d13302'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paragraph',
    sa.Column('paragraph_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('paragraph_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('registration_time', sa.DateTime(), nullable=False),
    sa.Column('highest_wpm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friendship',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('is_requested', sa.Boolean(), nullable=False),
    sa.Column('requesting_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['requesting_user'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('result',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('wpm', sa.Integer(), nullable=True),
    sa.Column('total_characters', sa.Integer(), nullable=False),
    sa.Column('characters', sa.JSON(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('words', sa.JSON(), nullable=False),
    sa.Column('correct_words', sa.JSON(), nullable=False),
    sa.Column('total_mistakes', sa.Integer(), nullable=False),
    sa.Column('mistake_characters', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.paragraph_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('friendship')
    op.drop_table('user')
    op.drop_table('paragraph')
    # ### end Alembic commands ###
