"""add mistake_words column to TypingResult

Revision ID: df322aa380a9
Revises: f3347697ae31
Create Date: 2025-05-12 13:39:06.628577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df322aa380a9'
down_revision = 'f3347697ae31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mistake_words', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('mistake_words')

    # ### end Alembic commands ###
