"""Add correct_characters field to TypingResult

Revision ID: f3347697ae31
Revises: 871694d13302
Create Date: 2025-05-02 20:36:12.903762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f3347697ae31'
down_revision = '871694d13302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_characters', sa.JSON(), nullable=False))
        batch_op.drop_column('characters')
        batch_op.drop_column('words')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('words', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('characters', sqlite.JSON(), nullable=False))
        batch_op.drop_column('correct_characters')

    # ### end Alembic commands ###
